# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 함께타는 택시풀링 캐빗
title_short: 캐빗
email: hello@cabbit.io
description: 함께 타고, 가격을 나누는 택시풀링 서비스 캐빗
# baseurl: "" # the subpath of your site, e.g. /blog
url: "https://cabbit.io" # the base hostname & protocol for your site
# pagenation: 5

copyright: Copyright @2016 Kanizsa Lab Co., Ltd, All rights reserved
facebook_username: helloCabbit
instagram_username: helloCabbit
# twitter_username: jekyllrb
# github_username:  jekyll

gems:
  - jekyll-sitemap
  - jekyll-feed

# Build settings
markdown: kramdown
